---
title: Birdy Beta
url: http://birdy-beta.siteleaf.net
timezone: UTC
collections:
  music:
    title: Music
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
analytics: 
typekit: 
description: The New Album Out 25 March featuring the new single Keeping Your Head
  Up
domain: http://officialbirdy.com/
company: Atlantic Records UK
email: hello@officialbirdy.com
facebook: https://www.facebook.com/BirdyMusic
twitter: https://twitter.com/officialbirdy
youtube: https://www.youtube.com/user/OfficialBirdy
instagram: https://www.instagram.com/birdyinstagram/
spotify: https://play.spotify.com/artist/2WX2uTcsvV5OnS0inACecP
soundcloud: https://soundcloud.com/officialbirdy
permalink: pretty
